
export const config = {
    server_url: process.env.SERVER_URL,
    socket_url: process.env.SOCKET_URL,
    sounds: {
        'EDM': [
            'edm-drums',
            'edm-marimba',
            'edm-piano1',
            'edm-piano2',
            'edm-piano3',
            'edm-spooky',
            'edm-synth1',
            'edm-synth2',
            'edm-synth3',
            'edm-synth4',
            'edm-guitar',
        ],
        'Chill': [
            'chill-drum',
            'chill-guitar1',
            'chill-music-box',
            'chill-piano1',
            'chill-piano2',
            'chill-piano3',
            'chill-spaceship',
            'chill-marimba',
        ],
        'Funk Pop': [
            'funkpop-bass1',
            'funkpop-bass2',
            'funkpop-chord1',
            'funkpop-drums1',
            'funkpop-drums2',
            'funkpop-piano1',
            'funkpop-trumpet',
            'funkpop-tuba',
        ],
        'Choir': [
            'choir1',
            'choir2',
            'choir3',
        ],
        'Cinematic': [
            'cinematic-harp1',
            'cinematic-flute1',
            'cinematic-piano1',
            'cinematic-piano2',
            'cinematic-piano3',
            'cinematic-piano4',
            'cinematic-piano5',
            'cinematic-frenchhorn1',
            'cinematic-frenchhorn2',
            'cinematic-windchimes',
            'cinematic-cymbal1',
            'cinematic-cymbal2',
            'cinematic-strings1',
            'cinematic-strings2',
            'cinematic-strings3',
        ],
        'Chords': [
            'C-major-low',
            'C-major-mid',
            'C-major-high',
            'C-minor-low',
            'C-minor-mid',
            'C-minor-high',
            'D-major-low',
            'D-major-mid',
            'D-major-high',
            'D-minor-low',
            'D-minor-mid',
            'D-minor-high',
            'E-major-low',
            'E-major-mid',
            'E-major-high',
            'E-minor-low',
            'E-minor-mid',
            'E-minor-high',
            'F-major-low',
            'F-major-mid',
            'F-major-high',
            'F-minor-low',
            'F-minor-mid',
            'F-minor-high',
            'G-major-low',
            'G-major-mid',
            'G-major-high',
            'G-minor-low',
            'G-minor-mid',
            'G-minor-high',
            'A-major-low',
            'A-major-mid',
            'A-major-high',
            'A-minor-low',
            'A-minor-mid',
            'A-minor-high',
            'B-major-low',
            'B-major-mid',
            'B-major-high',
            'B-minor-low',
            'B-minor-mid',
            'B-minor-high',
        ],
        'Guitar Riffs': [
            'riff1',
            'riff2',
            'riff3',
            'riff4',
            'riff5',
            'riff6',
            'riff7',
            'riff8',
            'riff9',
            'riff10',
            'riff11',
            'riff12',
            'riff13',
            'riff14',
            'riff15',
        ],
        'Sick beats': [
            'lofi-beat1',
            'lofi-beat2',
            'freestyle-rap-beat1',
            'bongos',
            'castanets',
            'simple-beat1',
            'simple-beat2',
            'simple-beat3',
            'simple-beat4',
            'drumset-crazy1',
            'claps',
        ],
        'Craziness': [
            'craziness'
        ]
    },
    congrats: [
        "You are a Bach 2.0!",
        "You are a Mozart Master!",
        "You are 1 step closer to composition fame!",
        "You will be on the radio in no time!",
        "Your skills are getting more and more like a pro pianist!",
        "You are a musical machine!",
        "Those layers were bars!",
        "You have those golden ears!",
        "Your partner can now jam out to your masterpiece!",
        "Share the song to show everyone how talented you are!",
        "This is better than Justin BieberU+2019s new hit!",
        "Might as well join Queen in their next gig!",
        "You are like the second coming of Beethoven!",
    ],
}