export default interface Layer {
    layerId: string,
    left: number,
    top: number,
    startTime: number,
    endTime: number,
    dropped: boolean,
    file: string,
    bucketUrl: string,
    memberId: string,
    stagingSoundName: string|null,
    stagingSoundBufferDate: string|null,
    stagingSoundBufferDuration: any,
    stagingSoundBuffer: Blob|null,
}
